INSERT INTO category (description) VALUES ('American');
Insert into category (description) values ('Italian');
Insert into category (description) values ('Mexican');
Insert into category (description) values ('Fast Food');
Insert into unit_of_measure (description) values ('Teaspoon');
Insert into unit_of_measure (description) values ('Tablespoon');
Insert into unit_of_measure (description) values ('Cup');
Insert into unit_of_measure (description) values ('Pinch');
Insert into unit_of_measure (description) values ('Ounce');
Insert into unit_of_measure (description) values ('Each');
Insert into unit_of_measure (description) values ('Dash');
Insert into unit_of_measure (description) values ('Pint');